language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "nightly"
install: "pip install -r requirements.txt"
script:
- cp config.DEFAULT.py config.py
- python honeypot.py test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eeffbf4b0a64c685f04d
    on_success: always
    on_failure: always
    on_start: never
